version: '3.8'
services:
  log-producer:
    build:
      context: ./log-producer
      dockerfile: Dockerfile
    container_name: log-producer
    ports:
      - "8081:8081"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_KAFKA_TOPIC_LOGS=logs
      - MANAGEMENT_OTLP_TRACING_ENDPOINT=http://jaeger:4317
      - MANAGEMENT_OTLP_METRICS_EXPORT_URL=http://jaeger:4317
      - MANAGEMENT_TRACING_SAMPLING_PROBABILITY=1.0
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
      - OTEL_RESOURCE_ATTRIBUTES_SERVICE_NAME=log-producer
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
    networks:
      - logs-system_default

networks:
  logs-system_default:
    external: true 