version: '3.8'
services:
  log-consumer:
    build:
      context: ./log-consumer
      dockerfile: Dockerfile
    container_name: log-consumer
    ports:
      - "8082:8082"
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/logsdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_OUTPUT_ANSI_ENABLED=always
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
    networks:
      - logs-system_default

networks:
  logs-system_default:
    external: true 